version: "3.6"

x-service: &base_service
  env_file: 
    - .env
  image: node_ms:latest
  networks:
    - app-network

services:
  gateway:
    image: gateway:latest
    ports:
      - 8080:80
    networks:
      - app-network

  hotel:    
    <<: *base_service
    ports:
      - ${hotel_port}:${hotel_port}
    command:
      - hotel

  
  profile:    
    <<: *base_service
    ports:
      - ${profile_port}:${profile_port}
    command:
      - profile
  
  auth:    
    <<: *base_service
    ports:
      - ${auth_port}:${auth_port}
    command:
      - auth

networks:
  app-network:
    driver: bridge
