version: "3.6"

x-service: &base_service
  env_file: 
    - .env
  build:
      context: .
  networks:
    - app-network

services:
  gateway:
    build:
      context: .
    ports:
      - 8080:80
    networks:
      - app-network

  hotel:    
    <<: *base_service
    ports:
      # - ${hotel_port}:${hotel_port}
      - 3000:3000
    command:
      - /app/services/hotel

  
  profile:    
    <<: *base_service
    ports:
      # - ${hotel_port}:${hotel_port}
      - 3001:3001
    command:
      - /app/services/profile
  
  auth:    
    <<: *base_service
    ports:
      # - ${hotel_port}:${hotel_port}
      - 3002:3002
    command:
      - /app/services/auth

networks:
  app-network:
    driver: bridge
