version: "3.6"

x-service: &base_service
  restart: always
  env_file: 
    - .env
  image: node_ms:latest
  networks:
    - app-network

services:
  gateway:
    image: gateway:latest
    ports:
      - 8080:80
    networks:
      - app-network

  hotel:    
    <<: *base_service
    ports:
      - ${hotel_port}:${hotel_port}
    command:
      - hotel

  
  profile:    
    <<: *base_service
    ports:
      - ${profile_port}:${profile_port}
    command:
      - profile
  
  auth:    
    <<: *base_service
    ports:
      - ${auth_port}:${auth_port}
    command:
      - auth

  #  db:
  #   image: mysql:latest
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: example
  #     MYSQL_DATABASE: HOTEL  
  #     MYSQL_USER: user  
  #     MYSQL_PASSWORD: 1234

networks:
  app-network:
    driver: bridge
